### ISSUE TITLE
New Suggestions

### ISSUE THREAD

**Issue by thunderboldi** [FarbstoffRSL/RSL-Helper#101]
Hello, is it possible to add the following functions?
For clan chief:

- Evaluation on activity at the Clanboss of the ClanMembers (CSV/DB).
- Evaluation on act

ivity on clan tasks (task,number,gold)

For other daily processes

- Execution of the daily todos (collect Gems,7 Brutal attack etc.) as freely definable tasks to work off.
- Or is 20 x on ice golem 20 finished then make 20 x dragon on 20. Provided one is finished one comes back to the base.
- Predefine TagTeam attacks

**Comment by BlackHawk3000** [comment]
`Hello, is it possible to add the following functions?
For clan chief:

Evaluation on activity at the Clanboss of the ClanMembers (CSV/DB).
Evaluation on act
ivity on clan tasks (task,number,gold)`

Maybe in future

`For other daily processes

Execution of the daily todos (collect Gems,7 Brutal attack etc.) as freely definable tasks to work off.
Or is 20 x on ice golem 20 finished then make 20 x dragon on 20. Provided one is finished one comes back to the base.
Predefine TagTeam attacks`

So far Plarium does not allow it like that, because it is multiple actions and not an auto-click (one action, what Plarium means by that).

**Comment by Dwza** [comment]
This feature was decliend.
