### ISSUE TITLE
saying no admin rights after the update

### ISSUE THREAD

**Issue by rejimaru** [FarbstoffRSL/RSL-Helper#122]
i just updated it right now for the latest version, and when i re-started it says this. 
i am the only user for my pc.. 
![rsl](https://user-images.githubusercontent.com/84756759/130710937-597f4784-361c-4d68-bbf6-a4ea9dc6a0fc.PNG)

**Comment by BlackHawk3000** [comment]
Only for you :) 
https://www.youtube.com/watch?v=nNVdaJXYCbA

**Comment by Dwza** [comment]
Hi @sacp 
actually the helper always required to be run with admin permissions since the helper is installed on c drive and mostly programms dont have permission to create files or use dll files from windows folder.
a workaround may could be to copy a lot of windows dll's into the install folder and try to make run as standalone as possible.
but to keep it more simple, this will not happen :)
farbstoff tried to install it to other locations but for some reason there were several issues everytime... mainly reading the game stream. and if the helper cant read the stream, than the helper can't help :D

ps: I'm sorry for blackhawk3000's sacasm... there are so often request with mainly the same issue and no matter how often you tell people, they always come with the same problem. how ever, i dont think he meant it in a bad way :)

i hope my explanation was clear for you.

regrads
dwza
