### ISSUE TITLE
RSL Helper won't launch

### ISSUE THREAD

**Issue by gryki** [FarbstoffRSL/RSL-Helper#124]
Perhaps a screenshot can help:

![image](https://user-images.githubusercontent.com/88828239/131019285-e458af00-f0d6-4a53-901e-145dd923a1df.png)

So Visual C++ 2015-2019 is installed.
Issue is, that RSL Helper Icon won't even show up in the task bar. 
The loading screen just stays hanging.
(Started as admin, installed as admin, ran update ofc etc.)

Any ideas?

**Comment by WOM8AT** [comment]
same issue with me on this. After  "open rsl helper have fun!" nothing happens. doesnt start the autoclicker window. any help? using the latest update.

**Comment by WOM8AT** [comment]
above comment in english "Wait until your update of RAID is through and then test again Incl. restart"

**Comment by chris101rose** [comment]
I'm having the same problem. Tried rebooting the computer and attempting again, but no luck.

**Comment by drakon78** [comment]
Had the same problem. first hat the wrong visual c++ 2015. uninstalled it. Installed first 2013 then 2015-2019 after that it worked . i am not sure if 2013 is really needed or just reainstall of th 2015-2019 needed. Also check if you have installed the correct architectur (32 bit or 64 bit) , i have installed 64bit since my system is 64 bit

**Comment by chris101rose** [comment]
Thanks @drakon78. I uninstalled my c++ and reinstalled and it worked. I tried just installing 2015-2019, but it didn't work until I installed 2013 as well. Hopefully this solution works for others too.

**Comment by BlackHawk3000** [comment]
is fixed please try new version, if the issue still there open a new issue :)
