### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by et-ent** [FarbstoffRSL/RSL-Helper#130]
I love your tool.  Thanks so much if this doesn't fit in with your plans I am sure what you have planned is way better than what I can think of.

I am a F2P player and I try to maximize my resources.  Because of the limited energy, you get the game as a lot of idle game time.  I like to level my champions 1 run short of maxing them and then finishing them off in the Sparring pit.  Because of the idle time I rarely get behind.  For example, for rank 2 champions I only run them 9 times when I have double experience.  Then I do the last level in the sparing pit because while 1 more run could level them up it will waste some experience so by utilizing the sparing pit I further maximize my energy.  Is there a chance you can add the ability to set what level to take the champions to?  Instead of level 20 being the max level for a rank 2 I can set it to level 19.

**Comment by Dwza** [comment]
this was requested before and will be implemented in future. but there are currently more important things :D
i wonder how you have idle time, if you get all enery every day....from all things where you can get it, you should have enough ^^
ok, i save my energy for events to get the max out of it. simply leveling without event and xp bonus makes no sense at all :D

**Comment by razzam21** [comment]
That is awesome.  I was pretty confident someone smarter than me would have requested it but I couldn't find it in the list of issues so I added it.  

The only time I am leveling food is when I have an XP boost.  And since it takes 6.5 hours to fully replenish your energy and only a few minutes to use it when farming food there is some idle time in the game.  Like right now I have my game up but it isn't doing anything because I don't have any energy but my sparring pit is capping off a few champions.  When I don't have an XP boost there are two things I look at.  An event where I can double dip.  If there isn't then I get my potions to a level that is above what would be necessary for a fusion so that I am always prepared for one when they come and I don't have to worry about and then it is farming dragon because you always need better gear.
Thanks again.  Awesome tool.  It helps to prevent burnout.

**Comment by et-ent** [comment]
That is awesome. I was pretty confident someone smarter than me would have requested it but I couldn't find it in the list of issues so I added it.

The only time I am leveling food is when I have an XP boost. And since it takes 6.5 hours to fully replenish your energy and only a few minutes to use it when farming food there is some idle time in the game. Like right now I have my game up but it isn't doing anything because I don't have any energy but my sparring pit is capping off a few champions. When I don't have an XP boost there are two things I look at. An event where I can double dip. If there isn't then I get my potions to a level that is above what would be necessary for a fusion so that I am always prepared for one when they come and I don't have to worry about and then it is farming dragon because you always need better gear.
Thanks again. Awesome tool. It helps to prevent burnout.

**Comment by Dwza** [comment]
> Thanks again. Awesome tool. It helps to prevent burnout.
Oh yes, it does :D

**Comment by Dwza** [comment]
This feature was added. Closing this thread.
