### ISSUE TITLE
Localize file

### ISSUE THREAD

**Issue by FullSilence** [FarbstoffRSL/RSL-Helper#21]
Please add localize system for custom localize

**Comment by Dwza** [comment]
what you want, change language or what? currently language is more or less hardcoded. this may will be changed but not in near future since there are some other thins seem more important :D but thats farbstoffs decision.

**Comment by rbeurskens** [comment]
Please make it consistent at least. It can still be hard-coded. Most of the application uses English, which a lot people may understand, but in autosell settings, German is used. 
![image](https://user-images.githubusercontent.com/2340490/118416458-118ec280-b6b0-11eb-81b1-8c713ca26c8f.png)

**Comment by Dwza** [comment]
@rbeurskens this is because actually it wasnt planed to make this international ^^ actually it was build more or less for german community. but some members prefered english language so it got translated. Now there were more and more things came to it and some of them were german. farbstoff sayed the tool is a beta and the translation comes later... but yes, its just a few changes and i will tell him to add this in english as well. :D

**Comment by rbeurskens** [comment]
Sure, Thanks. I understand and I appreciate sharing it with a wider community. For beta stage, it already can do a LOT of things.

**Comment by Dwza** [comment]
I just told him, may in the next version this should be translated.
