### ISSUE TITLE
Helper will crash if opened after RAID.

### ISSUE THREAD

**Issue by Joseph3LK** [FarbstoffRSL/RSL-Helper#259]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.0.0

### PHP Version

Not sure?

### Bug description

Noticing this pattern for a few days now:

1. If Helper is opened after RAID both will be forced to close.
2. If Helper is opened before RAID, it will open RAID and everything works fine.

Something is causing both clients to close if Helper is ran after RAID.

### Steps to reproduce

Refer to comments.

### Relevant log output

```shell
Not sure.
```

**Comment by dfyz8-g** [comment]
the same problem

**Comment by Xirlith** [comment]
Hi, i have the same crash

**Comment by kamui86** [comment]
its  crashing today again, there was no update in raid while yesterday RSL downloaded some update but again it crashes when raid opens.

**Comment by Dwza** [comment]
RSL Helper need to be started before Raid to work properly. This is because RSL needs to listen to some files when raid is starting. Its kind of a problem to do this while raid is running because some files are in use than and cant be processed. So this doesnt seem to be a bug in my point of view.
I will close this one so far.
@kamui86 If you forcing an other issue, please open a new issue or visit the discord to get help.
