### ISSUE TITLE
Suggestion: DoomTower Next clicker

### ISSUE THREAD

**Issue by LeonvZ311** [FarbstoffRSL/RSL-Helper#263]
### What is your idea of enhancement?

I use an autoclicker on Android and make this click the Next button on DoomTower runs. This automates the whole run from trash to boss. Would it be possible to add such an option?

**Comment by Aipoc76** [comment]
use effective resources is already there...   click that and then start it.. you will run DT till you hit the boss.

**Comment by Dwza** [comment]
Just like Aipoc76 mentioned, this function already exists. Yes, it stops at boss. In order to be sure you have set the correct team. If if you press play in rsl helper again, it will run boss as long as you have keys to run the boss.
since this feature is already implemented, i will close this issue.
