### ISSUE TITLE
Socket Failure

### ISSUE THREAD

**Issue by bkrohn1** [FarbstoffRSL/RSL-Helper#274]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

RSL Helper updater 1.60

### Bug description

![RSL Helper error msg](https://user-images.githubusercontent.com/98062565/150232876-3b43f988-fea9-413d-ba48-250b7b8ebae7.jpg)
When I use the updater for the first time it pops up with the socket failure error message in German.

### Steps to reproduce

Start up RSL Helper. It opens updater and then the error message.

**Comment by Areeweblind** [comment]
Second

**Comment by PompachJohnson** [comment]
![Anwendungsfehler 20 1 2022 г  1_05_44](https://user-images.githubusercontent.com/97984485/150243823-9fcfcc13-bbfa-4537-a7fb-8c351c10436c.png)
That happened to me

**Comment by bkrohn1** [comment]
I also got that one in my uninstall/delete journey to get this to work
again.

**Comment by yifeik** [comment]
Same error happened to me today.

**Comment by Wholfen** [comment]
Having same problem...
![RSLHelper error 01192022](https://user-images.githubusercontent.com/95461502/150270341-ee7b20f6-b713-48f3-aeb4-3c4d660c12e3.jpg)

**Comment by BlackHawk3000** [comment]
No Updater anymore, more information and new files on Discord. 

https://discord.gg/farbstoff

**Comment by Wholfen** [comment]
Thank You! Sent from Mail for Windows From: BlackHawk3000Sent: Wednesday, January 19, 2022 10:58 PMTo: FarbstoffRSL/RSL-HelperCc: Wholfen; CommentSubject: Re: [FarbstoffRSL/RSL-Helper] Socket Failure (Issue #274) No Updater anymore, more information and new files on Discord.https://discord.gg/farbstoff—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by bkrohn1** [comment]
I don't understand how this was closed. Your link brings me to a German language page on Discord. There isn't link to download the new version of RSL Helper. I have version 2.20.2.1 dated 1-13-22. That version brings up the updater and I get the original error message. If there is a newer version please provide the link. Sending me to Discord where there is no posted file that I can find, is not solving the issue. Thanks.

**Comment by Wholfen** [comment]
Try this link: https://drive.google.com/uc?export=download&id=1T8UlFpxaMxfWe7WOZPGbt5padh1N1pgw Sent from Mail for Windows From: bkrohn1Sent: Thursday, January 20, 2022 3:57 PMTo: FarbstoffRSL/RSL-HelperCc: Wholfen; CommentSubject: Re: [FarbstoffRSL/RSL-Helper] Socket Failure (Issue #274) I don't understand how this was closed. Your link brings me to a German language page on Discord. There isn't link to download the new version of RSL Helper. I have version 2.20.2.1 dated 1-13-22. That version brings up the updater and I get the original error message. If there is a newer version please provide the link. Sending me to Discord where there is no posted file that I can find, is not solving the issue. Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by bkrohn1** [comment]
TYVM
