### ISSUE TITLE
Run problem issue

### ISSUE THREAD

**Issue by changyong-song** [FarbstoffRSL/RSL-Helper#442]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

5.80.0

### RSL Helper Version

v3.4.2.7

### Description

Followed installation step of RSL Helper but It stops and doesn't go next like below capture.
![image](https://user-images.githubusercontent.com/111860108/186121546-fec3517e-5abb-4079-9760-2306e77a749e.png)

**Comment by Yeliab417** [comment]
I am having the same issue.  Anyone know a fix?
Already attempted un-install and re-install.

**Comment by Dwza** [comment]
go to `%appdata%\rslHelper\Config` open `umXXXXXRSLelper.ini` if you dont have extensions activated... you can see on the right side something with "configuration file" or some similar. open this file with a texteditor and check if your path to plarium.exe is correct. also, run updater as well since there is a newer version online.
