### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by VodzGaming** [FarbstoffRSL/RSL-Helper#48]
![image](https://user-images.githubusercontent.com/85075370/120114246-2a9a7780-c176-11eb-81fb-5085a696b2c0.png)
so i uninstalled and reinstalled and I updated from an older version and i even reset my pc after each of them so why is it not working anymore

**Comment by Dwza** [comment]
are you really running it as an admin?

**Comment by BlackHawk3000** [comment]
You can't do anything, Plarium has changed data. That's why some users get this error. Currently you can only wait until you do not get incorrect data.
This is our current state of affairs. If we have a solution we will contact our users.


Contact Farbstoff on his Discord , maybe he has time to look at the problem in the next days.
If he can get access to your RAID account, he may be able to isolate the problem.
