### ISSUE TITLE
No update for game version 3.50.0. Current RSL Helper version is outdated.

### ISSUE THREAD

**Issue by YuriyPent** [FarbstoffRSL/RSL-Helper#481]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

6.50.0

### RSL Helper Version

v.3.8

### Description

Assistant does not start, updates are required.
![image](https://user-images.githubusercontent.com/12219558/217787186-c31a98e9-8410-4365-b62b-cabd9dfe44c0.png)

### Steps to reproduce

Run helper.

**Comment by avramemil** [comment]
Operating system
Windows 10

Systemlanguage
English (EN)

Current Game-Version
V4.1.1.12

RSL Helper Version
V1.0

Description
hello!
This problem seems to apeared again.
I tried to update the application and to reinstall it but it not work out.

![error_rsl](https://github.com/FarbstoffRSL/RSL-Helper/assets/107368465/40b073cb-eabd-439c-85de-b99c722c4896)
