### ISSUE TITLE
Auto Refill is not working

### ISSUE THREAD

**Issue by nberanger** [FarbstoffRSL/RSL-Helper#497]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

7.10.0

### RSL Helper Version

v3.8.12.3

### Bug description

When you set the autoclicker to use refills, it will either not use any at all, or just use one. Eventually it gets stuck on the screen where the game prompts you to buy a refill.

Similarly, if you set the autoclicker to "Run effective resources", it uses what you have and then gets stuck at the refill screen. Even when your energy starts to build back up again, it does not use it. Instead it sits with the pop up window prompting you to purchase a refill, or use on from your storage.

### Steps to reproduce

Set the autoclicker to "Auto Refill", or "Run Effective Resources".

**Comment by krekre789** [comment]
I came here to report basicly the same. Has been the same issue since about two updates ago for me on the beta helper. For me it mostly uses some refills (from from about 1 to 5, every time a different amount) and then just stops. Also the spinning wheel on the bottom left turns off and it seems like it thinks the job is completed... It doesn't matter if I set it to "run infinitely" ot set it to 1000 runs. It always stops at a random amount of refills.

Changing click times didn't help either.

I really love the program and am very grateful your doing this. Just hope at some point you can fix this. Is this even a known issue? I'm happy to help finding the problem fwiw.

**Comment by nberanger** [comment]
So not sure what has changed... everything seemed to work fine for me when I left RSL Helper running over night. I haven't run any more updates, but things appear to be working correctly now <shrug>

**Comment by krekre789** [comment]
I still have the same issue. It did 11 refills the day before. Today it stopped after just 4....
