### ISSUE TITLE
issue with resolution and increase windows

### ISSUE THREAD

**Issue by Lorryanna** [FarbstoffRSL/RSL-Helper#8]
Hi,

My windows is configured in Settings / System / Display with 200% for "Change the size of text, apps, and other items" 
this pc is on a 4k 55'' TV so I need to increase everything to be confortable :)

Unfortunatly RSL-Helper seems not to appreciate and it displayed like this:
![image](https://user-images.githubusercontent.com/8207755/109354148-a1755b00-787d-11eb-80e0-20cc2df16204.png)

You can see at the bottom bar, everything is shrinked
I cannot launch the autoclicker because the start/stop button are not available (no way to scroll down the grey area)
RSL-Helper is not maximizable or resizable either, it could probably fix the issue

If I set to 100% RSL-Helper displays correclty (but too small for my setup :( and it affects all other apps)

**Comment by Dwza** [comment]
you can keep the resolution at 200%. To fix this issue, right click rsl_helper.exe, click properties, change to compability tab and on the bottom of the window you can change die high dpi settings. click change high dpi and in the opening window you click the checkbox in the bottom... select system advanced and save everything. from now on the helper will ignore your 200% setting. idk if i got all words correct, but you can find some screens in faq when you search for dpi. may they help, even if they are in german. otherwise reply here (what you could do in any case) 
regrads

**Comment by Lorryanna** [comment]
thanks it works !

Sorry about tha faq, but when I checked it and I saw it was in german I skipped :)
